mod.ActiveOrder = {
    "No",
    "Yes",
}

mod.BiomeDisplayOrder = {
        "Erebus",
        "Oceanus",
        "Mourning_Fields",
        "Tartarus",
        "Ephyra",
        "Sea",
        "Mount_Olympus",
        "Summit",
    }

mod.TypeDisplayOrder = {
    "Battle",
    "Special",
    "Boss",
}

mod.LocationDisplayOrder = {
    Erebus = {
        Battle = {
            "F_Opening01",
            "F_Opening02",
            "F_Opening03",
            "F_Combat01",
            "F_Combat02",
            "F_Combat03",
            "F_Combat04",
            "F_Combat05",
            "F_Combat06",
            "F_Combat07",
            "F_Combat08",
            "F_Combat09",
            "F_Combat10",
            "F_Combat11",
            "F_Combat12",
            "F_Combat13",
            "F_Combat14",
            "F_Combat15",
            "F_Combat16",
            "F_Combat17",
            "F_Combat18",
            "F_Combat19",
            "F_Combat20",
            "F_Combat21",
            "F_Combat22",
        },
        Special = {
            "F_PreBoss01",
            "F_PostBoss01",
            "F_Shop01",
            "F_Reprieve01",
            "F_Story01",
            "Chaos_01",
            "Chaos_02",
            "Chaos_03",
            "Chaos_04",
            "Chaos_05",
            "Chaos_06",

        },
        Boss = {
            "F_MiniBoss01",
            "F_MiniBoss02",
            "F_MiniBoss03",
            "F_Boss01",
            "F_Boss02",
        },
    },
    Oceanus = {
        Battle = {
            "G_Combat01",
            "G_Combat02",
            "G_Combat03",
            "G_Combat04",
            "G_Combat05",
            "G_Combat06",
            "G_Combat07",
            "G_Combat08",
            "G_Combat09",
            "G_Combat10",
            "G_Combat11",
            "G_Combat12",
            "G_Combat13",
            "G_Combat14",
            "G_Combat15",
            "G_Combat16",
            "G_Combat17",
            "G_Combat18",
            "G_Combat19",
            "G_Combat20",
            "B_Combat01",
            "B_Combat05",
            "B_Combat06",
            "B_Combat07",
            "B_Combat08",
            "B_Combat10",
            "B_Combat21",

        },
        Special = {
            "G_Intro",
            "G_PreBoss01",
            "G_PostBoss01",
            "G_Shop01",
            "G_Reprieve01",
            "G_Story01",
        },
        Boss = {
            "G_MiniBoss01",
            "G_MiniBoss02",
            "G_MiniBoss03",
            "G_Boss01",
            "G_Boss02",
        },
    },
    Mourning_Fields = {
        Battle = {
            "H_Combat01",
            "H_Combat02",
            "H_Combat03",
            "H_Combat04",
            "H_Combat05",
            "H_Combat06",
            "H_Combat07",
            "H_Combat08",
            "H_Combat09",
            "H_Combat10",
            "H_Combat11",
            "H_Combat12",
            "H_Combat13",
            "H_Combat14",
            "H_Combat15",
        },
        Special = {
            "H_Intro",
            "H_PreBoss01",
            "H_PostBoss01",
            "H_Bridge01",
        },
        Boss = {
            "H_MiniBoss01",
            "H_MiniBoss02",
            "H_Boss01",
            "H_Boss02",
        },
    },
    Tartarus = {
        Battle = {
            "I_Combat01",
            "I_Combat02",
            "I_Combat03",
            "I_Combat04",
            "I_Combat05",
            "I_Combat06",
            "I_Combat07",
            "I_Combat08",
            "I_Combat09",
            "I_Combat10",
            "I_Combat11",
            "I_Combat12",
            "I_Combat13",
            "I_Combat14",
            "I_Combat15",
            "I_Combat16",
            "I_Combat17",
            "I_Combat18",
            "I_Combat19",
            "I_Combat20",
            "I_Combat21",
            "I_Combat22",
            "I_Combat23",
        },
        Special = {
            "I_Intro",
            "I_PreBoss01",
            "I_PreBoss02",
            "I_PostBoss01",
            "I_Shop01",
            "I_Reprieve01",
            "I_Story01",
            "I_ChronosFlashback01",
            --"I_TwoExits",
            "I_DeathAreaRestored", 
            "EndCredits01",
            "Dream_Intro",
            "Dream_PostBoss01",
            "Dream_PostBoss02",
            "Dream_PostBoss03",
        },
        Boss = {
            "I_MiniBoss01",
            "I_MiniBoss02",
            "I_MiniBoss03",
            "I_Boss01",
            "C_Boss01",

        },
    },
    Ephyra = {
        Battle = {
            "N_Combat01",
            "N_Combat02",
            "N_Combat03",
            "N_Combat04",
            "N_Combat05",
            "N_Combat06",
            "N_Combat07",
            "N_Combat08",
            "N_Combat09",
            "N_Combat10",
            "N_Combat11",
            "N_Combat12",
            "N_Combat13",
            "N_Combat14",
            "N_Combat15",
            "N_Combat16",
            "N_Combat17",
            "N_Combat18",
            "N_Combat19",
            "N_Combat20",
            "N_Combat21",
            "N_Combat22",
            "N_Combat23",
            "N_Sub01",
            "N_Sub02",
            "N_Sub03",
            "N_Sub04",
            "N_Sub05",
            "N_Sub06",
            "N_Sub07",
            "N_Sub08",
            "N_Sub09",
            "N_Sub10",
            "N_Sub11",
            "N_Sub12",
            "N_Sub13",
            "N_Sub14",
            "N_Sub15",
        },
        Special = {
            "N_Opening01",
            "N_PreHub01",
            "N_Hub",
            "N_PreBoss01",
            "N_PostBoss01",
            "N_Shop01",
            "N_Story01",
        },
        Boss = {
            "N_MiniBoss01",
            "N_MiniBoss02",
            "N_Boss01",
            "N_Boss02",
        },
    },
    Sea = {
        Battle = {
            "O_Combat01",
            "O_Combat02",
            "O_Combat03",
            "O_Combat04",
            "O_Combat05",
            "O_Combat06",
            "O_Combat07",
            "O_Combat08",
            "O_Combat09",
            "O_Combat10",
            "O_Combat11",
            "O_Combat12",
            "O_Combat13",
            "O_Combat14",
            "O_Combat15",
        },
        Special = {
            "O_Intro",
            "O_PreBoss01",
            "O_PostBoss01",
            --"O_Devotion01",
            "O_Shop01",
            "O_Reprieve01",
            "O_Story01",
        },
        Boss = {
            "O_MiniBoss01",
            "O_MiniBoss02",
            "O_Boss01",
            "O_Boss02",
        },
    },
    Mount_Olympus = {
        Battle = {
            "P_Combat01",
            "P_Combat02",
            "P_Combat03",
            "P_Combat04",
            "P_Combat05",
            "P_Combat06",
            "P_Combat07",
            "P_Combat08",
            "P_Combat09",
            "P_Combat10",
            "P_Combat11",
            "P_Combat12",
            "P_Combat13",
            "P_Combat14",
            "P_Combat15",
            "P_Combat16",
            "P_Combat17",
            "P_Combat18",
            "P_Combat19",
        },
        Special = {
            "P_Intro",
            "P_PreBoss01",
            "P_PostBoss01",
            "P_Reprieve01",
            "P_Shop01",
            "P_Story01",
        },
        Boss = {
            "P_MiniBoss01",
            "P_MiniBoss02",
            "P_Boss01",
        },
    },
    Summit = {
        Battle = {
            "Q_Combat01",
            "Q_Combat02",
            "Q_Combat03",
            "Q_Combat04",
            "Q_Combat05",
            "Q_Combat06",
            "Q_Combat07",
            "Q_Combat08",
            "Q_Combat09",
            "Q_Combat10",
            "Q_Combat11",
            "Q_Combat12",
            "Q_Combat13",
            "Q_Combat14",
            "Q_Combat15",
            "Q_Combat16",
            
        },
        Special = {
            "Q_Intro",
            "Q_PreBoss01",
            "Q_PostBoss01",
            "Q_Story01",
        },
        Boss = {
            "Q_MiniBoss01",
            "Q_MiniBoss02",
            "Q_MiniBoss03",
            "Q_MiniBoss04",
            "Q_MiniBoss05",
            "Q_Boss01",
            "Q_Boss02",
        },
    },

}

if rom.mods['NikkelM-Zagreus_Journey'] then
    table.insert(mod.BiomeDisplayOrder, "Tartarus_H1")
    table.insert(mod.BiomeDisplayOrder, "Asphodel")
    table.insert(mod.BiomeDisplayOrder, "Elysium")
    table.insert(mod.BiomeDisplayOrder, "Styx")
    
    OverwriteTableKeys(mod.LocationDisplayOrder,{
		Tartarus_H1 = {
            Battle = {
                "A_Combat01",
                "A_Combat02",
                "A_Combat03",
                "A_Combat04",
                "A_Combat05",
                "A_Combat06",
                "A_Combat07",
                "A_Combat08A",
                "A_Combat08B",
                "A_Combat09",
                "A_Combat10",
                "A_Combat11",
                "A_Combat12",
                "A_Combat13",
                "A_Combat14",
                "A_Combat15",
                "A_Combat16",
                "A_Combat17",
                "A_Combat18",
                "A_Combat19",
                "A_Combat20",
                "A_Combat21",
                "A_Combat22",
                "A_Combat23",
                "A_Combat24",
                "A_Combat25",
            },
            Special = {
                "RoomOpening",
                "A_PreBoss01",
                "A_PostBoss01",
                "A_Story01",
                "A_Reprieve01",
                "A_Shop01",
            },
            Boss = {
                "A_MiniBoss01",
                "A_MiniBoss02",
                "A_MiniBoss03",
                "A_MiniBoss04",
                "A_Boss01",
                "A_Boss02",
                "A_Boss03",
            },
		},
		Asphodel = {
            Battle = {
                "X_Combat01",
                "X_Combat02",
                "X_Combat03",
                "X_Combat04",
                "X_Combat05",
                "X_Combat06",
                "X_Combat07",
                "X_Combat08",
                "X_Combat09",
                "X_Combat10",
                "X_Combat21",
                "X_Combat22",
            },
            Special = {
                "X_Intro",
                "X_PreBoss01",
                "X_PostBoss01",
                "X_Story01",
                "X_Reprieve01",
                "X_Shop01",
            },
            Boss = {
                "X_Wrapping01",
                "X_MiniBoss01",
                "X_MiniBoss02",
                "X_Boss01",
                "X_Boss02",
            },
		},
		Elysium = {
            Battle = {
                "Y_Combat01",
                "Y_Combat02",
                "Y_Combat03",
                "Y_Combat04",
                "Y_Combat05",
                "Y_Combat06",
                "Y_Combat07",
                "Y_Combat08",
                "Y_Combat09",
                "Y_Combat10",
                "Y_Combat11",
                "Y_Combat12",
                "Y_Combat13",
                "Y_Combat14",
                "Y_Combat15",
            },
            Special = {
                "Y_Intro",
                "Y_PreBoss01",
                "Y_PostBoss01",
                "Y_Story01",
                "Y_Reprieve01",
                "Y_Shop01",
            },
            Boss ={
                "Y_MiniBoss01",
                "Y_MiniBoss02",
                "Y_MiniBoss03",
                "Y_Boss01",
            },
		},
		Styx = {
            Battle = {
                "D_Combat01",
                "D_Combat02",
                "D_Combat03",
                "D_Combat04",
                "D_Combat05",
                "D_Combat06",
                "D_Mini01",
                "D_Mini02",
                "D_Mini03",
                "D_Mini04",
                "D_Mini05",
                "D_Mini06",
                "D_Mini07",
                "D_Mini08",
                "D_Mini09",
                "D_Mini10",
                "D_Mini11",
                "D_Mini12",
                "D_Mini13",
                "D_Mini14",
                "RoomChallenge01",
                "RoomChallenge02",
                "RoomChallenge03",
                "RoomChallenge04",
            },
            Special = {
                "D_Intro",
                "D_Hub",
                "D_Reprieve01",
                "E_Intro",
                "E_Story01",
                "Return01",
                "Return02",
                "Return03",
                "Return04",
                "Return05",
                "Return06",
            },
            Boss ={
                --"D_MiniBoss01",
                --"D_MiniBoss02",
                --"D_MiniBoss03",
                --"D_MiniBoss04",
                "D_Boss01",
                "CharonFight01",
            },
		}
	})
 
end